# Site settings
title:                Federico Vegetti
description:          random political research things
baseurl:              ""

# Build settings
markdown:     kramdown
highlighter:  rouge

# Accounts
twitter_username:     fedeunderstress
github_username:      federicovegetti
linkedin_username:    federicovegetti

# Blog posts
paginate:             5
paginate_path:        "/blog/page:num/"
future:               true
