# Site settings
title:                Federico Vegetti
description:          political and behavioral data scientist
baseurl:              ""

# Build settings
markdown:     kramdown
highlighter:  rouge

# Accounts
twitter_username:     fedeunderstress
github_username:      federicovegetti
linkedin_username:    federicovegetti


paginate:             5
paginate_path:        "/blog/page:num/"